server:
  servlet:
    context-path: /store
Spring:
  datasource:
    url: jdbc:h2:./store
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /console
